### PR TITLE
Update resort.py

### PR DESCRIPTION
**Pull request by freeflowthought**
fix the bug in your code

### CODE REVIEW

**Comment by lesywix** [comment]
Hi @freeflowthought , thx for your PR. Your solution is great. But could you pls describe what's the bug of the previous solution? Thx.

**Comment by freeflowthought** [comment]
just add the edge case prevention for type checking.
I added the implementation with func in this suggestions, that does better purpose to separate of concerns.
https://github.com/freeflowthought/Algorithms/commit/1c081d0ab669872f288f4f5c9e35b298e6950e27

**Comment by lesywix** [comment]
Yes, it looks great. Could you cherry-pick the commit to this PR then I'll merge the PR. Thx

**Comment by freeflowthought** [comment]
sure, I just opened a new PR for the refactoring work. I just directly updated the file so it's a new PR.

**Comment by lesywix** [comment]
Nice, thx for your work.

**Pull request merged**
